### ISSUE TITLE
Overhanging decorations on terrain generation

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#139]
**Describe the bug**
Generate some terrain with decorations that occur at edge of realm and they can go beyond the limits of the realm. 

**To Reproduce**
1. Create new realm with `/realm new`
2. Teleport to new realm with `/realm tp 2`
3. Generate some terrain with `/realm gen 2 v2 v2 10 123`
4. Bam! Tree canopy outside of the realm boundaries.

**Expected behavior**
Decorations and other nodes should always be contained within the realm boundaries to avoid unexpected behaviour, glitching, etc. If we decide that decorations are allowed to overhang, then we still need a method to clean them up when `/realm gen` is run again on the same realm. It will be very convenient to be able to re-run the terrain/forest generator on the same realm until a desired state is obtained.

**Screenshots**
![image](https://user-images.githubusercontent.com/61996662/180626076-e08444f1-734a-48b2-81cb-74dc2b5efa10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - v5.5.1

**Comment by lukasgolson** [comment]
I'll look into removing all blocks on the outside of the realm when building walls.

**Comment by pauldpickell** [comment]
Can we also add a method to display the seed for the last terrain generation like what currently exists for `/realm seed` or just output it to chat when the terrain is generated without an input seed?

**Comment by lukasgolson** [comment]
> Can we also add a method to display the seed for the last terrain generation like what currently exists for `/realm seed` or just output it to chat when the terrain is generated without an input seed?

This is a quick addition, I'll add it in with the fix for the overhang.
