### ISSUE TITLE
Add readme.md for magnify

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#156]
Would like to see an informative readme.md file for the magnify mod:

- [x] A short description of the mod and what it does
- [x] Some screenshots
- [x] Instructions for adding new species and assets (how to, where to)
- [x] Documentation for the `magnify.register_species` function

**Comment by Lowie375** [comment]
Alright, can do! Will likely copy the README file from `magnify/magnify` up to the main modpack folder (`magnify`) and leave just the API documentation in the existing one

**Comment by pauldpickell** [comment]
Fixed by #159
