### ISSUE TITLE
Refactor MC_Helpers into MC_Core

### ISSUE THREAD

**Issue by lukasgolson** [ubc-minetest-classroom/Minetest_Classroom#168]
**Is your feature request related to a problem? Please describe.**
We have a core mod file for the Minetest classroom game. To simplify dependencies and keep clean architecture, I think it might be a good idea to move 'core' functionality used by all classroom mods into this existing mod.

**Describe the solution you'd like**
I would like to see the mc_helper files moved into mc_core and all dependencies updated towards the existing core mod.

**Describe alternatives you've considered**
An alternative would be to leave things as they are.

**Comment by Lowie375** [comment]
Definitely agree with this proposal.
`mc_core` currently serves no other purpose than to instantiate the `minetest_classroom` global table, thus it makes sense to merge Minetest Classroom's helper functions into the "core" mod to keep everything in one place.
Alternatively, we could move the instantiation of the `minetest_classroom` global table into `mc_helpers` (convenience), but I think moving the helper functions into `mc_core` would make the most sense architecturally
