### ISSUE TITLE
Decouple `magnify` and `mc_teacher`

### ISSUE THREAD

**Issue by Lowie375** [ubc-minetest-classroom/Minetest_Classroom#18]
Presently, `mc_teacher` is dependent on `magnify`, since part of its functionality (the Plant Compendium button) needs access to objects defined in and handled by `magnify`.

Ideally, `mc_teacher` should be able to run independent of `magnify`. I'm currently unsure of how the current systems in place could be refactored to make this possible, but hope to find some way to make it happen.

**Comment by pauldpickell** [comment]
I wonder if `magnify` could be a standalone mod? There is no reason for it to be dependent on `mc_core` or plug into the global `minetest_classroom`. The only part that is truly integrated with `mc_teacher` is the plant compendium with the buttons in the teacher menu. But that could also default to a new tab on the basic inventory formspec. If we decide to integrate it with the existing inventory and crafting formspec, then it opens the possibility that we could make use of that space for other things like `rules`, player management, realm management, etc.

**Comment by Lowie375** [comment]
You're right, `magnify` probably could be made into a standalone mod, with the compendium accessible from the inventory. That would also allow everyone to access the compendium, not just teachers, which means that there won't need to be a compendium button in the student menu either.
Will look into how custom tabs for the inventory formspec work, then begin refactoring `magnify` + `mc_teacher` as necessary

**Comment by Lowie375** [comment]
Have completed some refactoring, making `magnify`'s plant compendium accessible through an inventory tab instead of the teacher menu. This, combined with a few other refactors, decouples `magnify` and `mc_teacher`.

**Comment by Lowie375** [comment]
#39 recoupled `magnify` and `mc_teacher`. Ideally, [line 29 in `mc_teacher/gui_dash.lua`](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/develop/mods/mc_teacher/gui_dash.lua#L29) should be removed outright, since `mc_teacher` doesn't call anything from the `magnify` object after that declaration

**Comment by pauldpickell** [comment]
Got it, fixed.

**Comment by pauldpickell** [comment]
@Lowie375 can you confirm that `magnify` no longer depends on `mc_helpers` and if so remove the dependency in the [mod.conf file](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/f82a0d8dfd90d9dcbfcc8ffed6f94c54030ed42d/mods/magnify/mod.conf#L3)?

**Comment by Lowie375** [comment]
`magnify` currently depends on `table.has` in `mc_helpers/init.lua` - can copy this into `magnify` as a local function

**Comment by Lowie375** [comment]
As of [commit d35ae87](https://github.com/ubc-minetest-classroom/Minetest_Classroom/commit/d35ae87cd4fbdd9661c4df5f66353326b5e7fd04), `magnify` is no longer dependent on `mc_helpers`
