### ISSUE TITLE
Dynamic trees (like the Minecraft mod of the same name)

### ISSUE THREAD

**Issue by lukasgolson** [ubc-minetest-classroom/Minetest_Classroom#21]
" A dynamic tree is a multi-block structure of rooty soil, branches, and leaves blocks that has many advances over the Vanilla Minetest tree structures. The formation of the tree starts with a seed. This seed is either planted by hand or the seed has a chance of planting itself if left on the ground in a suitable location.  The tree then grows from a sapling, slowly increasing it's size over time, into a full sized tree. The tree can then be chopped down at it's base and all of the wood claimed at once." (Paraphrased from https://www.curseforge.com/minecraft/mc-mods/dynamictrees)

I propose that we implement a basic tree growth simulation for different species of tree using cellular automata for canopy growth, branch network logic for trunk and branches, and a very basic soil moisture/nutrient/mycelia model that averages soil saturation levels according to linear distance from a "source" block (or other simple model).

This feature would allow students to watch forests grow according to landscape characteristics and give us the potential to simulate multi-generation disturbance regimes.

This idea needs to be expanded further, but see https://www.curseforge.com/minecraft/mc-mods/dynamictrees for a good overview of what I'm talking about.

**Comment by pauldpickell** [comment]
Not sure if any Minetest mods currently exist to extend node shapes for the branching patterns, but some new 3D models to work with would probably be a requisite for implementing this. Another thing that comes to mind is integrating the probability of seed self-planting as a function of disturbance. For example: pine species dropping serotinous cones and then a wildfire triggering their germination; shade -tolerant species having higher probability of germination under the canopy; shade-intolerant species having higher probability of germination following a harvest or canopy-gap creation.

**Comment by pauldpickell** [comment]
Closing as there are existing mods that are available for dynamic tree growth.
