### ISSUE TITLE
Feature Request: Delay Display of IP Whitelist

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#229]
When the server tab is clicked in the teacher controller, there is a significant delay as it takes time to return all the IP addresses. This also causes lag/delay whenever other actions are taken on the server tab, like exiting from the ban manager. It might be helpful to only display the full IP list when requested. Maybe we can add a button to show it in a popup?

**Comment by Lowie375** [comment]
Whitelist has been moved from the main server tab to a popup on `features/unified_gui_ii` as of [`4ff019f`](https://github.com/ubc-minetest-classroom/minetest_classroom/commit/4ff019f16b1990a78522a728eb9b158d7dd4c9a2), which should reduce lag when opening the server tab. However, that doesn't fix the fundamental issue.
Will add a button to show the whitelisted IPs to the popup - we may also want to consider some other ways to condense the displayed IPs for readability and better load times

**Comment by pauldpickell** [comment]
Solved by #231
