### ISSUE TITLE
Instanced classrooms using "empty world" option are not walled

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#230]
**Describe the bug**
When an instanced classroom is created with the "empty world" option selected, it does not have walls. 

**To Reproduce**
1. Open the teacher controller.
2. Navigate to the classrooms tab.
3. Create a new classroom, set the type to instanced, and the generation to "empty world". Use any decorators, seed, and sea level.
4. Observe a classroom without walls.

**Expected behavior**
All classrooms should have walls. This does not seem to occur with the "schematic" option.

**Comment by pauldpickell** [comment]
@Lowie375 Is it possible that the voxel manipulator in `Realm:GenerateTerrain()` is overwriting the barriers generated in `mc_worldManager.GetCreateInstancedRealm()`?

Stack Trace:
- [mc_teacher\callbacks.lua Line 309:](https://github.com/ubc-minetest-classroom/minetest_classroom/blob/83f601be09ff4855785bbd0fb1028976950f8027/mods/mc_teacher/callbacks.lua#L309) `new_realm = mc_worldManager.GetCreateInstancedRealm(realm_name, player, nil, true, realm_size)`
- [mc_worldmanager\init.lua Line 101:](https://github.com/ubc-minetest-classroom/minetest_classroom/blob/83f601be09ff4855785bbd0fb1028976950f8027/mods/mc_worldmanager/init.lua#L101) `realm:CreateBarriers()`
- [mc_teacher\callbacks.lua Line 332:](https://github.com/ubc-minetest-classroom/minetest_classroom/blob/83f601be09ff4855785bbd0fb1028976950f8027/mods/mc_teacher/callbacks.lua#L332) `new_realm:GenerateTerrain(rgi.seed, rgi.sea_level, rgi.height_func, rgi.dec_func, param_table)`

**Comment by lukasgolson** [comment]
I haven't looked at this code since last year so I might be mistaken, but I just wanted to pop in and see if realm:CreateBarriers() is being called when creating empty worlds.

E.g., see how schematics are being spawned:

https://github.com/ubc-minetest-classroom/minetest_classroom/blob/main/mods/mc_worldmanager/realm/realmSchematicSaveLoad.lua#L209

I'll look at this issue further later this week if this hasn't been resolved by then.

**Comment by pauldpickell** [comment]
Yes, `realm:CreateBarriers()` is [called](https://github.com/ubc-minetest-classroom/minetest_classroom/blob/83f601be09ff4855785bbd0fb1028976950f8027/mods/mc_worldmanager/init.lua#L101) during `mc_worldManager.GetCreateInstancedRealm`.

Just as a simple test, the chat commands seem to create the realm, barriers, and terrain as expected on the server:
`\realm new`
`\realm gen [realmid] v1 v1 1234 30`

Now I am just realizing the the barriers are created [again](https://github.com/ubc-minetest-classroom/minetest_classroom/blob/83f601be09ff4855785bbd0fb1028976950f8027/mods/mc_worldmanager/commands.lua#L219) at the end of the "gen" command.

**Comment by pauldpickell** [comment]
Fixed by [5537976](https://github.com/ubc-minetest-classroom/minetest_classroom/commit/5537976ca24315b570e533286a826a04968e10e3).
