### ISSUE TITLE
Plant compendium updates

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#44]
1. When accessed from the inventory, the "Back" button in the `magnify` formspec should return to the "Plant compendium" tab in the inventory instead of exiting the user. 

2. King bolete (9 in the compendium) seems to be missing a wrapper as the text runs over the image. Not sure if this was an import issue or is systematic. I did not see any others that behaved this way.

3. Suggest removing the URLs from the formspec for now since it seems to clutter the space and is not really functional. 

4. Finally, [lines 125-148 in /magnify/init.lua](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/0c944fe113997a4befe64fbaf501328bb0a816d0/mods/magnify/init.lua#L125-L148) have some odd spacing and indention going on. Can you clean that up so that it is easier to read? 

The current behaviour is that you open the compendium, and the default selection in the list is 1. You click to another plant, which changes `context.species_selected` to the index for that plant, then you click "Standard view", look at it, and it exits on the `Back` button. When you go back into the compendium, again the default selection in the list is 1, but `context.species_selected` is still storing the previous `event.index`. So if you just click "Standard view", even with 1 in the list highlighted, it redirects you to the last species viewed. I think our desired behaviour here is that we want the current `event.index` to always be highlighted in the list or default to 1 when first loaded.
Edit: updating this to also note that the same behaviour exists for the "My coordinates" formspec in `mc_student`. Whatever change is applied here, should also be applied [there](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/0c944fe113997a4befe64fbaf501328bb0a816d0/mods/mc_student/init.lua#L376-L391).

In the "Technical view", I think we can remove the photo (since that is already in the "Standard view") and instead use `item_image[<X>,<Y>;<W>,<H>;<item name>]` to show all the Minetest nodes that are associated with the species. This would be more useful for using that view as a debugger or an aid to the player for identifying the species in the Minetest world.

**Comment by Lowie375** [comment]
1. Likely not possible with the current implementation, since there doesn't seem to be an easy way to open the inventory via the MineTest API. This leaves us with a few options:
    - Leave the implementation as-is (last resort)
    - Comb through the inventory-handling source code and see if a method can be located and run to re-launch the inventory. This may be tedious and likely would not be a stable approach, since that may cause breaking changes down the line if we need to change MineTest versions
    - Moving the viewer formspec directly into the inventory. Implementing this will require some work, since we'd need to modify the way everything is displayed, but it should be possible using the `sfinv` API. This is also the best option of the 3 for long-term stability, since we wouldn't be relying on undocumented `minetest` methods
2. This is a systematic issue with the V1 formspec, since `label` elements aren't constrained to a set width and height. A workaround was implemented in V2: using `textarea` elements, which are constrained, causing overflow text to be cut off. This isn't a perfect solution, so it's worth looking into merging all data into a single, wrapped info box or two info boxes (height/conservation status/region, additional info)

- 3 and 4 are simple fixes - we'll get on that today
    - 4 seems to be the result of mixing spaces and tabs, whoops! We should probably make our tab style more consistent

5. Desired behaviour for `context.species_selected` was present in the teacher menu implementation of the compendium, will work on re-implementing that in the inventory implementation. Suspect it may have to do with badly-handled data.
    - Can also apply this change to `mc_student` once it's handled in `magnify`
6. Noted, will use an `item_image` instead. May be worth having it dynamically change as different nodes are selected using a system similar to the one currently present in the [`tutorialbook`](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/tutorialbook/mods/mc_tutorial_framework/init.lua#L114) branch

**Comment by pauldpickell** [comment]
6. It's more effort, but I wonder if it could pay off in the long term if we show _all_ the nodes registered with a particular species, instead of just the pointed node? This could include several nodes for a single species (leaves, branches/stem, fruit, flower), which could make it difficult to handle dynamically in the formspec since some species might have all of those or just stem and leaves nodes. I am not sure what the `item_image` actually looks like, as I have never used it.

**Comment by Lowie375** [comment]
Update on 5: it seems like this is only happening the first time the inventory is launched - if you switch tabs and re-enter the plant compendium, the species given by `context.species_selected` is selected. This is definitely odd, so will look deeper into what's going on
EDIT: Have done some testing, and it seems like the `get` code for the inventory tab is not re-run on re-launch - ~~I wonder if this has something to do with the inventory not explicitly closing?~~ No, the inventory is just lazy. Will see if there's a way to force it to refresh (EDIT: there is - this fixes the issue)
If we handle 1 by moving the viewer directly into the player inventory, this may fix itself

**Comment by Lowie375** [comment]
> It's more effort, but I wonder if it could pay off in the long term if we show _all_ the nodes registered with a particular species, instead of just the pointed node?

Considering the way formspecs are created, I think this could be done. We'd just need to add some dynamic dimension-handling code, which shouldn't be too hard to create as long as an area for the item images is allocated in the technical view formspec

> I am not sure what the `item_image` actually looks like, as I have never used it.

Nor have I, but we might as well try it and find out.
UPDATE: `item_image` displays the inventory image of a given node, as expected - may be more useful to do a mix of models and inventory images

**Comment by Lowie375** [comment]
3 through 6 in the task list above have been handled!

**Comment by Lowie375** [comment]
1 and 2 in the task list have been handled as of commit [`2da7c66`](https://github.com/ubc-minetest-classroom/Minetest_Classroom/commit/2da7c667bf96dcf2f502dda589473efe329d8aa8) on `magnify`!
