### ISSUE TITLE
Bug: mc_worldmanager crashes on initiation

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#62]
Using `develop`, when a new world is initiated from the game menu, the server crashes with the following output:

> ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'mc_worldmanager' in callback on_newplayer(): ...\Minetest_Classroom\mods\mc_worldmanager/realm/realm.lua:77: table index is nil
> ERROR[Main]: stack traceback:
> ERROR[Main]: 	...\Minetest_Classroom\mods\mc_worldmanager/realm/realm.lua:77: in function 'New'
> ERROR[Main]: 	....\games\Minetest_Classroom\mods\mc_worldmanager\init.lua:35: in function 'GetSpawnRealm'
> ERROR[Main]: 	...\games\Minetest_Classroom\mods\mc_worldmanager/hooks.lua:5: in function <...\games\Minetest_Classroom\mods\mc_worldmanager/hooks.lua:3>
> ERROR[Main]: 	...st\minetest-5.4.1-win64\bin\..\builtin\game\register.lua:422: in function <...st\minetest-5.4.1-win64\bin\..\builtin\game\register.lua:406>

When joining the world again from the main menu, it works just fine.

**Comment by lukasgolson** [comment]
~~Bug was introduced in merge from PR #61; I'm looking through the changes to find it.~~

Scratch that, it was introduced in the hotfix; looking into it further
