### ISSUE TITLE
Bug: unsatisfied dependencies in signs

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#63]
Current output from `develop`:

> ERROR[Main]: mod "signs" has unsatisfied dependencies:  "dye"
> ERROR[Main]: mod "signs_road" has unsatisfied dependencies:  "dye"

I cannot find this mod by name and it is also not included in the `display_modpack` [repo](https://github.com/pyrollo/display_modpack).

**Comment by jocelynbachmann** [comment]
I'm not getting this error when running develop locally, even "/giveme dye:black" produces no errors for me, and puts black dye in the inventory. It doesn't seem like this actually needs to be listed as a dependency, as dyes are built-in. Maybe 'dye' could just be deleted from the dependencies of signs and signs_road? Removing it didn't produce any errors for me locally, but I'm not sure why I'm not getting either of these errors in the first place.

**Comment by pauldpickell** [comment]
Odd, because `dye` is not currently distributed with `Minetest_Classroom`, but I do see that it is a default mod in `minetest_game`. My error is local when loading a world in `Minetest_Classroom`. It is easy enough to add it now that I know where it is.

**Comment by pauldpickell** [comment]
Fixed by [003e229](https://github.com/ubc-minetest-classroom/Minetest_Classroom/commit/003e229a5885f38f2a5416fe72a2bc998ddb76a4).
