### ISSUE TITLE
Feature: Make magnifying glass tool work better standalone

### ISSUE THREAD

**Issue by Lowie375** [ubc-minetest-classroom/Minetest_Classroom#70]
Proposed improvements to make the magnifying glass work better as a standalone tool:
- Move tool give/take code to a helper mod (`mc_toolhandler`) to allow for wider use of the tool
  - Likely to be done on `features/tool-menu` branch due to backend needs
  - Could also be integrated into `mc_student` and `mc_teacher`, since the give/take code across all 3 tools is very similar
- Make the tool droppable by default + add metadata to make the tool undroppable if desired
- Add a crafting recipe for the tool:
  ```
   - G G         G G -
   - G G   AND   G G -     [OR]     - G   AND   G -
   S - -         - - S              S -         - S
  ```
  where `G = default:glass` and `S = group:stick`

**Comment by pauldpickell** [comment]
Also, need to consolidate `magnify`, `magnify_default_nodes` and `magnify_flower_nodes` into a new modpack.

**Comment by Lowie375** [comment]
Tool give/take code has been abstracted out of `magnify` on the `features/tool-menu` branch as part of the tool give/take refactor. Other `magnify`-related changes will be made on `magnify` directly, then merged into `develop` and/or `features/tool-menu`

**Comment by Lowie375** [comment]
> * Make the tool droppable by default + add metadata to make the tool undroppable if desired

A temporary workaround for implementing this could be adding a check for the presence of the `mc_core` mod to the `on_drop` event. That way, the tool will be able to be dropped everywhere outside of the MineTest Classroom.

For the long-term, it would probably be better to provide options for tools like this in a configuration file, an optional mod, through metadata, or something similar. However, some of these approaches have problems of their own:

- Using metadata would allow this to be handled easily internally. However, if the magnify tool needed to be given manually, the people giving the tool would need to know the metadata to add to give players an undroppable copy of the tool, which would not make emergency tool-giving very intuitive
- With one tool, an optional "patch" mod could work well. With multiple tools, however, this likely would not scale well. Using a configuration file would have some similar consequences, in addition to introducing some extra coupling within the tool mods
