### ISSUE TITLE
Feature: Real-world coordinates

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#77]
In `map.conf` files for `Minetest_Classroom` realm schematics, it would be nice to store variables that describes the map projection parameters used to create real world maps. Since Minetest worlds use a cartesian coordinate system, it makes sense to support importing map schematics that are projected to UTM. Then, we can develop a simple position translator that converts Minetest coordinates to real UTM easting-northing and latitude-longitude pairs. To do this, we need to know the real-world coordinates (in the NAD83/WGS84 datum) for a location in the map schematic.

Solution: Create a position translator mod that uses the HUD to display the current real-world position in latitude/longitude and easting/northing units. Add to `map.conf` files the following variables:

- `UTM_zone` = `integer` in range of 1-60
- `UTM_map_origin`  = `table` with key-value pairs indicating the `easting` and `northing` values for the map schematic origin at `{x=0,z=0}`.

This small feature update would make it much easier to navigate and edit realms as well as implement new tools that could be dependent on this feature such as GPS. More practically, I see this feature being a critical asset for placing schematics and objects within realms and also finding and editing real-world locations.

**Comment by pauldpickell** [comment]
Here is the math for converting between UTM and lat/lon: [A HIGHLY ACCURATE WORLD WIDE ALGORITHM FOR THE TRANSVERSE MERCATOR MAPPING (ALMOST)](https://icaci.org/files/documents/ICC_proceedings/ICC2007/documents/doc/THEME%202/oral%201/2.1.2%20A%20HIGHLY%20ACCURATE%20WORLD%20WIDE%20ALGORITHM%20FOR%20THE%20TRANSVE.doc)

And here is an example of [the algorithm implemented in the PROJ4 library](https://github.com/OSGeo/PROJ/blob/019dad3524e434edd7a35cd87251ad4eaab08614/src/projections/tmerc.cpp#L240-L256) (written in C++).

The exact method might not be needed since player position might only be updated with integer precision.

**Comment by lukasgolson** [comment]
Update: In-progress

**Comment by pauldpickell** [comment]
Reopening for one last request: add elevation to the HUD. 

For terrain generation, the input sea level needs to be stored for the realm and then `y` values above this level are positive and `y` values below this level are negative (relative to the realm). 

For digital twin worlds, like MKRF, we might use two options in the `map.conf`: 
- Parameter specifying if elevation `y` is exact in the map (e.g., MKRF512 is already built from sea level, so if you dig all the way down, you have reached sea level)
- Parameter specifying the relative elevation to add/subtract from the minimum `y` value in the map. This might be useful in the case that we do not want to define/store/serve all the below-ground terrain, but still want to preserve elevation in the map.
