### ISSUE TITLE
Feature: Species locator for finding plant nodes in the world

### ISSUE THREAD

**Issue by Lowie375** [ubc-minetest-classroom/Minetest_Classroom#86]
> Edit (PDP): Consider using `item_image_button[<X>,<Y>;<W>,<H>;<item name>;<name>;<label>]` for this under the technical view.

Currently implemented as a button in the plant compendium's technical viewer

Implementation note from #85:
> [...] do be aware that the current locator implementation may be laggy (due to the use of a MineTest searching function), unsure how to optimize without an entire function rewrite (which may not result in significant optimization improvements)

- `minetest.find_node_near()` is slow, hence why the search has been limited to a 120-node radius for now. Help is wanted for creating a more optimized search algorithm

**Comment by lukasgolson** [comment]
I've looked into this briefly; It seems that minetest.find_node_near() might be the best we can do (without forking the Minetest engine or using PE injection). That said, I'll benchmark using the Lua Voxel Manipulator when I get a chance to see if I can come up with something slightly faster.

**Comment by pauldpickell** [comment]
Is the particle spawner visible to all?

**Comment by Lowie375** [comment]
The particle spawner (and trail) are only visible to the player that used the locator, since having particles appear seemingly randomly for all players did not make much sense. However, this could be changed if desired.

**Comment by pauldpickell** [comment]
Since this feature is working, I will close this issue as of #85.
